### ISSUE TITLE
There are no products

### ISSUE THREAD

**Issue by codekrishna1** [NoCode-Engine/extensions-bug-triage#1]
*1. Please Add an appropriate label to help hasten our response to your request.
   -  **There are no products**

*2. Describe the bug
      [A clear and concise description of what the bug is.]
  -  **There are no products**

*3. Please provide the steps to reproduce and if possible a minimal demo, video or screenshots of the problem
   - 
![image](https://github.com/NoCode-Engine/extensions-bug-triage/assets/149013685/3621bc6d-e4f5-44d6-92d5-393db5bbbf17)

*4. What is the expected behavior?
 -    I was expecting some products for framer pagination.

**Comment by gate3** [comment]
Hi @codekrishna1, apologies for the mixup. Please get the plugin here [https://doyinolarewaju.gumroad.com/l/framer-pagination-extension](https://doyinolarewaju.gumroad.com/l/framer-pagination-extension). 

In order to help others, can avoid this same issue. Can you help me understand how you arrived on  the profile page instead of the product page. Thanks
